# Histogramas con Numpy.

In [1]:
import numpy as np

In [2]:
np.random.seed(2020)

In [5]:
np.set_printoptions(precision=2)

In [6]:
c = np.random.laplace(loc=10,scale=3,size=10000)
c[:5]

array([ 7.81, 12.69,  4.33,  8.65, 13.21])

In [9]:
hist, bin_edges = np.histogram(c)

In [10]:
hist

array([   5,   30,  249, 1434, 6093, 1873,  274,   31,   10,    1])

In [12]:
bin_edges

array([-15.76, -10.12,  -4.48,   1.17,   6.81,  12.45,  18.1 ,  23.74,
        29.38,  35.02,  40.67])

In [13]:
hist.size , bin_edges.size

(10, 11)

In [17]:
mimn = c.min()
maxi = c.max()
n_bins = 10
bin_edges = np.linspace(start=mimn,stop=maxi, num=n_bins+1,endpoint=True)
bin_edges
x = (1,1,1,1,1,2,2,2,2,3,4,5,6,7,8,7,6,5,6,7,8,7,6,5,4,3,3,2,3,5,6,7,7,8)

In [19]:
#Contamos el numero de apariciones dentro de nuestros datos
contador = np.bincount(x)
contador


array([0, 5, 5, 4, 2, 4, 5, 6, 3])

In [22]:
hist,_ = np.histogram(x, range=(0,max(x)), bins=max(x)+1)

In [23]:
hist

array([0, 5, 5, 4, 2, 4, 5, 6, 3])

In [24]:
np.array_equal(contador,hist)

True